# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Configuration for pip (requirements.txt)
  - package-ecosystem: "pip"  # Specifies the pip ecosystem for requirements.txt
    directory: "/"  # Location of the requirements.txt file in your repository
    schedule:
      interval: "weekly"  # Dependabot will check for updates weekly

  # Configuration for Poetry
  - package-ecosystem: "poetry"  # Specifies the poetry ecosystem
    directory: "/"  # Location of the pyproject.toml file in your repository
    schedule:
      interval: "weekly"  # Dependabot will check for updates weekly
